name: tapp
description: A TAPP Engine project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

# Do not add dependencies with versions starting from ^ and ~.
# Versions should be fixed to avoid CI/CD build issues.
dependencies:
  app_settings: 4.1.8
  auto_route: 4.0.1
  carousel_slider: 4.1.1
  cupertino_icons: 1.0.2
  connectivity_plus: 2.3.4
  dio: 4.0.6
  firebase_core: 2.2.0
  firebase_messaging: 14.1.0
  flutter:
    sdk: flutter
  flutter_bloc: 8.0.1
  flutter_local_notifications: 12.0.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: 2.2.3+1
  flutter_screenutil: 5.5.3+2
  flutter_secure_storage: 5.0.2
  flutter_svg: 1.1.0
  intl: 0.17.0
  local_auth: 2.1.0
  logger: 1.1.0
  modal_bottom_sheet: 2.0.1
  package_info_plus: 1.4.2
  page_view_indicators: 2.0.0
  pin_code_fields: 7.4.0
  provider: 6.0.3
  pull_to_refresh:
    git:
      url: https://github.com/MaksimMarkevichCoherent/pull_to_refresh
  rxdart: 0.27.4
  shared_preferences: 2.0.15
  shimmer: 2.0.0
  url_launcher: 6.1.3

dev_dependencies:
  auto_route_generator: 4.0.0
  change_app_package_name: 1.1.0
  build_runner: 2.1.11
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1

#flutter_native_splash:
#  # Customize the parameters below, and run the following command in the terminal:
#  # flutter pub run flutter_native_splash:create
#  # Splash screen background color.
#  color: "#FAFAFA"
#  # Image must be a png file and should be sized for 4x pixel density.
#  image: assets/images/splash_image.png
#  # Background color for a dark mode.
#  color_dark: "#141631"
#  # Image must be a png file and should be sized for 4x pixel density.
#  image_dark: assets/images/splash_image_dark.png

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/country_flags/
    - assets/images/icons/
    - assets/images/logo/

#  fonts:
#    - family: Inter
#      fonts:
#        - asset: assets/fonts/Inter-Regular.ttf
#        - asset: assets/fonts/Inter-Medium.ttf
#        - asset: assets/fonts/Inter-SemiBold.ttf
