// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDjY6CwC0z2eXJZlqv39zE2NRD3HE4uo4',
    appId: '1:1074612101519:android:fe9a9b9f5254a970baebfa',
    messagingSenderId: '1074612101519',
    projectId: 'architecture-2d52e',
    storageBucket: 'architecture-2d52e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPQa4ZwwTRsgLSZabuWZLq7HxUm3-uIyI',
    appId: '1:1074612101519:ios:b7f730724dccbc00baebfa',
    messagingSenderId: '1074612101519',
    projectId: 'architecture-2d52e',
    storageBucket: 'architecture-2d52e.appspot.com',
    iosClientId: '1074612101519-5cq8fdo44loijvdkbhn2bbmj9unpv4gr.apps.googleusercontent.com',
    iosBundleId: 'com.architecture.tapp',
  );
}
